---
collections:
  - name: ansible.utils
    version: "2.11.0"        # ansible-core 2.15 호환
  - name: community.crypto
    version: "2.16.2"        # 2.15까지 테스트됨
  - name: community.general
    version: "7.4.0"         # ansible-core 2.15 지원 마지막 안정 버전
  - name: ansible.netcommon
    version: "5.2.1"         # 2.15 호환 확인됨
  - name: ansible.posix
    version: "1.5.4"         # 2.15에서도 안정
  - name: community.docker
    version: "3.8.1"         # 2.15 호환
  - name: kubernetes.core
    version: "2.4.0"         # 2.15 및 Kubespray 테스트 범위 내
