---
collections:
  - ansible.utils: ">=2.5.0"
  - community.crypto: ">=2.22.3"  
  - community.general: ">=7.0.0"
  - ansible.netcommon: ">=5.3.0"
  - ansible.posix: ">=1.5.4"
  - community.docker: ">=3.11.0"
  - kubernetes.core: ">=2.4.2"
