---
collections:
  - name: ansible.utils
    version: '>=2.5.0'
  - name: community.crypto
    version: '>=2.22.3'
  - name: community.general
    version: '>=7.0.0'
  - name: ansible.netcommon
    version: '>=5.3.0'
  - name: ansible.posix
    version: '>=1.5.4'
  - name: community.docker
    version: '>=3.11.0'
  - name: kubernetes.core
    version: '>=2.4.2'
